export const TOGGLE_DISPLAY_CART = "TOGGLE_DISPLAY_CART";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const REDUCE_CART_ITEM_QUANTITY = "REDUCE_CART_ITEM_QUANTITY";